#!/bin/python3

import math
import os
import random
import re
import sys
n=10
ar=[1,1,3,1,2,1,3,3,3,3]
# Complete the sockMerchant function below.
ar.sort()
print(ar)
i=0
k=0
while i<n-1:
    if(ar[i]==ar[i+1]):
        k=k+1
        i=i+2
    else:
        i=i+1

print(k)    
